[project]
name = "evolutionary-borrowing"
authors = ["Clarity Innovator"]
description = "A decentralized protocol for dynamic and adaptive lending mechanisms"
telemetry = false
requirements = []
[contracts.borrowing-evolution]
path = "contracts/borrowing-evolution.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
